'use client';

export interface ThemeDef {
  id: string;
  name: string;
  icon: string;
  // CSS custom properties for this theme
  vars: Record<string, string>;
}

// Each theme defines CSS variables that override the defaults.
// Variables: --background, --foreground, --card, --primary, --accent, --border, etc.
export const THEMES: ThemeDef[] = [
  {
    id: 'light',
    name: 'Light',
    icon: '☀️',
    vars: {
      '--background': 'oklch(1 0 0)',
      '--foreground': 'oklch(0.145 0 0)',
      '--card': 'oklch(1 0 0)',
      '--primary': 'oklch(0.205 0 0)',
      '--primary-foreground': 'oklch(0.985 0 0)',
      '--secondary': 'oklch(0.97 0 0)',
      '--muted': 'oklch(0.97 0 0)',
      '--muted-foreground': 'oklch(0.556 0 0)',
      '--accent': 'oklch(0.97 0 0)',
      '--border': 'oklch(0.922 0 0)',
      '--input': 'oklch(0.922 0 0)',
      '--ring': 'oklch(0.708 0 0)',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    icon: '🌙',
    vars: {
      '--background': 'oklch(0.145 0 0)',
      '--foreground': 'oklch(0.985 0 0)',
      '--card': 'oklch(0.205 0 0)',
      '--primary': 'oklch(0.922 0 0)',
      '--primary-foreground': 'oklch(0.205 0 0)',
      '--secondary': 'oklch(0.269 0 0)',
      '--muted': 'oklch(0.269 0 0)',
      '--muted-foreground': 'oklch(0.708 0 0)',
      '--accent': 'oklch(0.269 0 0)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--ring': 'oklch(0.556 0 0)',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    icon: '🌆',
    vars: {
      '--background': '#0a0a12',
      '--foreground': '#ff00ff',
      '--card': '#12121f',
      '--primary': '#00ffff',
      '--primary-foreground': '#0a0a12',
      '--secondary': '#1a1a2e',
      '--muted': '#1a1a2e',
      '--muted-foreground': '#8888aa',
      '--accent': '#ff00ff',
      '--accent-foreground': '#0a0a12',
      '--border': '#ff00ff44',
      '--input': '#00ffff22',
      '--ring': '#00ffff',
    },
  },
  {
    id: 'matrix',
    name: 'Matrix',
    icon: '🟢',
    vars: {
      '--background': '#000000',
      '--foreground': '#00ff41',
      '--card': '#0a0f0a',
      '--primary': '#00ff41',
      '--primary-foreground': '#000000',
      '--secondary': '#0d1a0d',
      '--muted': '#0d1a0d',
      '--muted-foreground': '#008f11',
      '--accent': '#00ff41',
      '--accent-foreground': '#000000',
      '--border': '#00ff4133',
      '--input': '#00ff4122',
      '--ring': '#00ff41',
    },
  },
  {
    id: 'hacker',
    name: 'Hacker',
    icon: '💻',
    vars: {
      '--background': '#0c0c0c',
      '--foreground': '#ffb000',
      '--card': '#161616',
      '--primary': '#ffb000',
      '--primary-foreground': '#0c0c0c',
      '--secondary': '#1e1e1e',
      '--muted': '#1e1e1e',
      '--muted-foreground': '#888866',
      '--accent': '#cc7700',
      '--accent-foreground': '#0c0c0c',
      '--border': '#ffb00033',
      '--input': '#ffb00022',
      '--ring': '#ffb000',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    icon: '🌊',
    vars: {
      '--background': '#f0f9ff',
      '--foreground': '#0c4a6e',
      '--card': '#ffffff',
      '--primary': '#0284c7',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e0f2fe',
      '--muted': '#e0f2fe',
      '--muted-foreground': '#0369a1',
      '--accent': '#0ea5e9',
      '--accent-foreground': '#ffffff',
      '--border': '#bae6fd',
      '--input': '#bae6fd',
      '--ring': '#0284c7',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    icon: '🌅',
    vars: {
      '--background': '#1a0f1e',
      '--foreground': '#fde68a',
      '--card': '#2d1b3d',
      '--primary': '#f59e0b',
      '--primary-foreground': '#1a0f1e',
      '--secondary': '#3d2851',
      '--muted': '#3d2851',
      '--muted-foreground': '#c4a8d8',
      '--accent': '#ec4899',
      '--accent-foreground': '#1a0f1e',
      '--border': '#f59e0b44',
      '--input': '#f59e0b22',
      '--ring': '#f59e0b',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    icon: '🌲',
    vars: {
      '--background': '#0a1a0a',
      '--foreground': '#d1e7d1',
      '--card': '#112211',
      '--primary': '#22c55e',
      '--primary-foreground': '#0a1a0a',
      '--secondary': '#1a2e1a',
      '--muted': '#1a2e1a',
      '--muted-foreground': '#88bb88',
      '--accent': '#16a34a',
      '--accent-foreground': '#0a1a0a',
      '--border': '#22c55e33',
      '--input': '#22c55e22',
      '--ring': '#22c55e',
    },
  },
  {
    id: 'royal',
    name: 'Royal',
    icon: '👑',
    vars: {
      '--background': '#1a0a2e',
      '--foreground': '#e9d5ff',
      '--card': '#2a1145',
      '--primary': '#a855f7',
      '--primary-foreground': '#1a0a2e',
      '--secondary': '#3d1a5c',
      '--muted': '#3d1a5c',
      '--muted-foreground': '#c4a8e8',
      '--accent': '#d4af37',
      '--accent-foreground': '#1a0a2e',
      '--border': '#a855f744',
      '--input': '#a855f722',
      '--ring': '#a855f7',
    },
  },
];

export const DEFAULT_THEME = 'light';
