// Pre-saved expression bank — 160+ expressions from basic to university research level
// All formatted to work with our recursive descent parser

export interface BankExpression {
  id: number;
  level: string;
  expression: string;
  description?: string;
}

export const EXPRESSIONS_BANK: BankExpression[] = [
  // ===== Level 1: Basic (2-Variable & Simple 3-Variable) =====
  { id: 1, level: 'Basic', expression: 'A+B', description: 'OR gate' },
  { id: 2, level: 'Basic', expression: 'A·B', description: 'AND gate' },
  { id: 3, level: 'Basic', expression: "A'+B'", description: 'OR of complements' },
  { id: 4, level: 'Basic', expression: "A'·B'", description: 'AND of complements' },
  { id: 5, level: 'Basic', expression: "(A+B)'", description: 'NOR (De Morgan)' },
  { id: 6, level: 'Basic', expression: "(A·B)'", description: 'NAND (De Morgan)' },
  { id: 7, level: 'Basic', expression: 'A⊕B', description: 'XOR' },
  { id: 8, level: 'Basic', expression: "(A⊕B)'", description: 'XNOR' },
  { id: 9, level: 'Basic', expression: 'A+B·C', description: 'OR with AND term' },
  { id: 10, level: 'Basic', expression: '(A+B)·C', description: 'AND with OR term' },
  { id: 11, level: 'Basic', expression: "A'·B+C", description: '3-variable SOP' },
  { id: 12, level: 'Basic', expression: "A·B'+C'", description: '3-variable SOP' },
  { id: 13, level: 'Basic', expression: 'A·(B+C)', description: 'Distributive' },
  { id: 14, level: 'Basic', expression: 'A·B·C', description: '3-input AND' },
  { id: 15, level: 'Basic', expression: 'A+B+C', description: '3-input OR' },
  { id: 16, level: 'Basic', expression: "A'·B'·C'", description: '3 complemented AND' },
  { id: 17, level: 'Basic', expression: "(A+B+C)'", description: '3-input NOR' },
  { id: 18, level: 'Basic', expression: "(A·B·C)'", description: '3-input NAND' },
  { id: 19, level: 'Basic', expression: "A'·B·C", description: 'Minterm m3' },
  { id: 20, level: 'Basic', expression: "A·B'·C'", description: 'Minterm m4' },
  { id: 21, level: 'Basic', expression: "A+B'·C", description: 'OR with complemented AND' },
  { id: 22, level: 'Basic', expression: "(A'+B)·C", description: 'POS form' },
  { id: 23, level: 'Basic', expression: 'A⊕B⊕C', description: '3-input XOR' },
  { id: 24, level: 'Basic', expression: "(A⊕B⊕C)'", description: '3-input XNOR' },
  { id: 25, level: 'Basic', expression: 'A·B+A·C+B·C', description: 'Majority function' },
  { id: 26, level: 'Basic', expression: "A'·B+A'·C+B·C", description: 'Carry function' },
  { id: 27, level: 'Basic', expression: 'A·(B⊕C)', description: 'AND with XOR' },
  { id: 28, level: 'Basic', expression: 'A⊕(B·C)', description: 'XOR with AND' },
  { id: 29, level: 'Basic', expression: "A'+B⊕C", description: 'OR with XOR' },
  { id: 30, level: 'Basic', expression: '(A+B)⊕C', description: 'XOR with OR' },

  // ===== Level 2: Medium (SOP, POS, & Multi-Output) =====
  { id: 31, level: 'Medium', expression: "A·B+A'·C", description: 'SOP form' },
  { id: 32, level: 'Medium', expression: "(A+B)·(A'+C)", description: 'POS form' },
  { id: 33, level: 'Medium', expression: "A'·B'·C+A·B'·C'+A·B·C", description: '3-minterm SOP' },
  { id: 34, level: 'Medium', expression: "A'·B'·C+A'·B·C'+A·B'·C+A·B·C", description: 'Σm(1,2,5,7)' },
  { id: 35, level: 'Medium', expression: "(A+B+C)·(A+B'+C')·(A'+B+C)·(A'+B'+C)", description: 'ΠM(0,3,4,6)' },
  { id: 36, level: 'Medium', expression: "(A⊕B)·C'+(A⊕C)·B'", description: 'XOR combinational' },
  { id: 37, level: 'Medium', expression: "A·B'·C+A'·B·C'+A·B·C'", description: '3-minterm SOP' },
  { id: 38, level: 'Medium', expression: "(A+B+C')·(A'+B'+C)", description: 'POS' },
  { id: 39, level: 'Medium', expression: '(A⊕B)+C', description: 'XOR OR C' },
  { id: 40, level: 'Medium', expression: "(A+B)⊕C'", description: 'XOR with complemented C' },
  { id: 41, level: 'Medium', expression: "A'·B+B·C+C·A'", description: 'Cyclic SOP' },
  { id: 42, level: 'Medium', expression: "A·B+B·C'+A'·C", description: 'Cyclic SOP' },
  { id: 43, level: 'Medium', expression: "A·(B'+C')+A'·(B+C)", description: 'Dual expression' },
  { id: 44, level: 'Medium', expression: "(A+B')·(B+C')·(A'+C)", description: '3-factor POS' },
  { id: 45, level: 'Medium', expression: "A⊕B⊕C'", description: 'XOR with complement' },
  { id: 46, level: 'Medium', expression: "(A·B)'+(B·C)'+(C·A)'", description: 'NAND sum' },
  { id: 47, level: 'Medium', expression: "(A+B·C)'+(B+A·C)'", description: 'Complex NAND' },
  { id: 48, level: 'Medium', expression: 'A·(B⊕C)+B·(A⊕C)', description: 'XOR network' },
  { id: 49, level: 'Medium', expression: '(A+B)·(B⊕C)', description: 'OR with XOR' },
  { id: 50, level: 'Medium', expression: "A'·B·C'+A·B'·C+A·B·C'", description: '3-minterm' },
  { id: 51, level: 'Medium', expression: "A·(B+C')+B·(C+A')", description: 'Distributive' },
  { id: 52, level: 'Medium', expression: '(A⊕B)·C+(A⊕C)·B', description: 'XOR network' },
  { id: 53, level: 'Medium', expression: "A'·B'·C+A·B'·C'+A'·B·C'+A·B·C", description: '4-minterm (even parity)' },
  { id: 54, level: 'Medium', expression: "A+B'·C'⊕C", description: 'Complex XOR' },
  { id: 55, level: 'Medium', expression: "(A'+B)·(A+C')·(B'+C)", description: '3-factor POS' },
  { id: 56, level: 'Medium', expression: "(A⊕B)'·(B⊕C)'", description: 'XNOR product' },
  { id: 57, level: 'Medium', expression: "A'⊕B⊕C", description: '3-input XOR' },
  { id: 58, level: 'Medium', expression: 'A·B+C·(A⊕B)', description: 'Full adder carry' },
  { id: 59, level: 'Medium', expression: "(A+C)·(B'+C')·(A'+B)", description: '3-factor POS' },
  { id: 60, level: 'Medium', expression: "(A+B+C)·(A'+B'+C')", description: 'Complement product' },

  // ===== Level 3: Hard (K-Map & Standard Circuits) =====
  { id: 61, level: 'Hard', expression: "A'·B'+A·B", description: 'XNOR' },
  { id: 62, level: 'Hard', expression: "A'·B+A·B'", description: 'XOR' },
  { id: 63, level: 'Hard', expression: "A'·B'·C+A'·B·C+A·B'·C+A·B·C", description: 'Odd parity generator' },
  { id: 64, level: 'Hard', expression: "A'·B'·C'+A'·B·C+A·B'·C'+A·B·C", description: 'Even parity generator' },
  { id: 65, level: 'Hard', expression: "A·B+A'·C'", description: 'K-map reduction' },
  { id: 66, level: 'Hard', expression: 'A⊕B⊕C', description: 'Full Adder Sum' },
  { id: 67, level: 'Hard', expression: 'A·B+B·C+A·C', description: 'Full Adder Carry' },
  { id: 68, level: 'Hard', expression: "A'·B'·C'+A'·B'·C+A·B'·C'+A·B·C", description: 'MUX logic' },
  { id: 69, level: 'Hard', expression: "A'·B'+B'·C+A'·C", description: 'K-map Σ(0,1,2,5)' },
  { id: 70, level: 'Hard', expression: "(A+B')·(B+C)·(A+C')", description: 'K-map POS' },
  { id: 71, level: 'Hard', expression: 'A⊕B⊕C', description: 'Full Subtractor Difference' },
  { id: 72, level: 'Hard', expression: "A'·B+B·C'+A'·C", description: 'Full Subtractor Borrow' },
  { id: 73, level: 'Hard', expression: "A'·B'·C+A·B'·C'+A·B·C", description: '3-bit Majority' },
  { id: 74, level: 'Hard', expression: "A+B·C+B'·C'", description: 'Complex SOP' },
  { id: 75, level: 'Hard', expression: '(A⊕B)⊕(A⊕C)', description: 'Double XOR' },
  { id: 76, level: 'Hard', expression: "A'·B·C+A·B'·C'+A'·B·C'+A·B'·C", description: '4-minterm' },
  { id: 77, level: 'Hard', expression: "(A+B+C)·(A+B'+C')·(A'+B+C')", description: '3-factor POS' },
  { id: 78, level: 'Hard', expression: "(A·B)'⊕(B·C)'", description: 'NAND XOR' },
  { id: 79, level: 'Hard', expression: '(A⊕B)·(B⊕C)', description: 'XOR product' },
  { id: 80, level: 'Hard', expression: "A'·B+A·B'+A·C", description: '3-term SOP' },
  { id: 81, level: 'Hard', expression: "(A+B')·(A'+C)·(B+C')", description: '3-factor POS' },
  { id: 82, level: 'Hard', expression: "A'⊕(B+C)", description: 'XOR with OR' },
  { id: 83, level: 'Hard', expression: "(A⊕B)'+(A⊕C)'", description: 'XNOR sum' },
  { id: 84, level: 'Hard', expression: "A·(B⊕C)'+A'·(B⊕C)", description: 'XNOR mux' },
  { id: 85, level: 'Hard', expression: "A'·B'·C'+A'·B·C+A·B'·C+A·B·C'", description: 'Even parity checker' },
  { id: 86, level: 'Hard', expression: "A'·B'·C+A·B'·C'+A'·B·C'+A·B·C", description: 'Odd parity checker' },
  { id: 87, level: 'Hard', expression: 'A⊕1', description: 'NOT via XOR' },
  { id: 88, level: 'Hard', expression: '(A⊕B)⊕0', description: 'Buffer via XOR' },
  { id: 89, level: 'Hard', expression: "A·(B'+C)+A'·(B+C')", description: 'Complex mux' },
  { id: 90, level: 'Hard', expression: "A'+B'·C+B·C'", description: 'A + (B⊕C)' },

  // ===== Level 4: Complex (Multi-Output & Optimized) =====
  { id: 91, level: 'Complex', expression: 'A⊕B⊕C', description: 'Sum (Arithmetic Unit)' },
  { id: 92, level: 'Complex', expression: 'A·B+A·C+B·C', description: 'Carry (Arithmetic Unit)' },
  { id: 93, level: 'Complex', expression: "A'·B+A'·C+B·C", description: 'Borrow (Arithmetic Unit)' },
  { id: 94, level: 'Complex', expression: "A'·B'·C'+A·B'·C'", description: 'BCD to Excess-3 bit' },
  { id: 95, level: 'Complex', expression: "B'·C+B·C'", description: 'BCD to Excess-3 (B⊕C)' },
  { id: 96, level: 'Complex', expression: "A+B+C'", description: 'BCD to Excess-3 bit' },
  { id: 97, level: 'Complex', expression: 'A·B', description: 'Multiplier partial product' },
  { id: 98, level: 'Complex', expression: 'A·C⊕B·A', description: 'Multiplier cross term' },
  { id: 99, level: 'Complex', expression: 'C·A+A·C·A·B', description: 'Multiplier carry' },
  { id: 100, level: 'Complex', expression: 'A+B+C', description: 'Priority encoder valid' },
  { id: 101, level: 'Complex', expression: 'B+C', description: 'Priority encoder MSB' },
  { id: 102, level: 'Complex', expression: 'C', description: 'Priority encoder LSB' },
  { id: 103, level: 'Complex', expression: "((A⊕B)⊕C)'", description: 'XNOR of 3 XOR' },
  { id: 104, level: 'Complex', expression: "(A+B+C)·(A'+B'+C')", description: 'Complement AND' },
  { id: 105, level: 'Complex', expression: "A'·B'+B·C+C·A'", description: 'Cyclic SOP' },
  { id: 106, level: 'Complex', expression: '(A⊕B)·C+A·(B⊕C)', description: 'XOR network' },
  { id: 107, level: 'Complex', expression: "(A+B')·(B+C')·(A'+B)", description: '3-factor POS' },
  { id: 108, level: 'Complex', expression: 'A⊕B⊕C⊕1', description: '4-input XOR with 1' },
  { id: 109, level: 'Complex', expression: 'A·(B⊕C)⊕B·(A⊕C)', description: 'Complex XOR network' },
  { id: 110, level: 'Complex', expression: '(A+B)⊕(B+C)⊕(A+C)', description: 'Triple XOR' },
  { id: 111, level: 'Complex', expression: "(A·B)'·(A+B)'", description: 'NAND AND NOR' },
  { id: 112, level: 'Complex', expression: "(A⊕B)·(A⊕C)'", description: 'XOR AND XNOR' },
  { id: 113, level: 'Complex', expression: "A'·B·C+A·B'·C+A·B·C'+A'·B'·C'", description: 'All even minterms' },
  { id: 114, level: 'Complex', expression: "A·B+A'·C'+B'·C'", description: 'Consensus theorem' },
  { id: 115, level: 'Complex', expression: "(A⊕B)'+(B⊕C)'", description: 'XNOR sum' },
  { id: 116, level: 'Complex', expression: 'A+B⊕C', description: 'OR with XOR' },
  { id: 117, level: 'Complex', expression: "(A·B·C)'+(A'·B'·C')'", description: 'Double NAND' },
  { id: 118, level: 'Complex', expression: '(A⊕B)+(B⊕C)+(A⊕C)', description: 'Triple XOR sum' },
  { id: 119, level: 'Complex', expression: 'A·(B⊕C)+(A⊕B)·C', description: 'XOR tree' },
  { id: 120, level: 'Complex', expression: '(A+B)·(B⊕C)+(A+C)·(A⊕B)', description: 'Complex product-sum' },

  // ===== Level 5: University Research (AOI, MUX, Advanced) =====
  { id: 121, level: 'Research', expression: 'A·B+C·(A⊕B)', description: 'AOI logic' },
  { id: 122, level: 'Research', expression: '(A·B)⊕(B·C)⊕(A·C)', description: 'Triple XOR of ANDs' },
  { id: 123, level: 'Research', expression: '(A+B)·(B⊕C)', description: 'OR AND XOR' },
  { id: 124, level: 'Research', expression: 'A·(B+C)⊕B·(A+C)', description: 'Symmetric XOR' },
  { id: 125, level: 'Research', expression: "(A·B)'⊕C", description: 'NAND XOR' },
  { id: 126, level: 'Research', expression: "(A+B)'·C+A·B·C'", description: 'NOR AND NAND' },
  { id: 127, level: 'Research', expression: "A·(B⊕C)'+A'·(B⊕C)", description: 'XNOR mux' },
  { id: 128, level: 'Research', expression: "(A·B+C)'+A·(B+C)'", description: 'Double NAND' },
  { id: 129, level: 'Research', expression: "(A⊕B)·C'+(A⊕C)·B'", description: 'XOR decoder' },
  { id: 130, level: 'Research', expression: "A·B'·C+A'·B·C+A·B·C'", description: '3-minterm SOP' },
  { id: 131, level: 'Research', expression: "A'·B'·C+A·B'·C'+A'·B·C'", description: '3-minterm SOP' },
  { id: 132, level: 'Research', expression: "(A+B+C')·(A'+B'+C)", description: 'POS form' },
  { id: 133, level: 'Research', expression: 'A⊕(B·C)+B⊕(A·C)', description: 'Double XOR' },
  { id: 134, level: 'Research', expression: "(A·B⊕C)·(A+B·C')", description: 'Complex product' },
  { id: 135, level: 'Research', expression: '(A+B·C)⊕(B+A·C)', description: 'Symmetric XOR' },
  { id: 136, level: 'Research', expression: "A'·(B+C)⊕B·(A+C')", description: 'XOR with mux' },
  { id: 137, level: 'Research', expression: 'A·B⊕B·C⊕A·C', description: 'Triple XOR' },
  { id: 138, level: 'Research', expression: "(A·B)'·C+A·(B+C)'", description: 'NAND + NOR' },
  { id: 139, level: 'Research', expression: "A·(B'⊕C)+A'·(B⊕C')", description: 'Complex XOR mux' },
  { id: 140, level: 'Research', expression: "(A+B⊕C)·(A'+B'⊕C')", description: 'XOR in POS' },
  { id: 141, level: 'Research', expression: "A·B'+B·C'+C·A'", description: 'Ring oscillator SOP' },
  { id: 142, level: 'Research', expression: "A'·B+B'·C+C'·A", description: 'Cyclic complement' },
  { id: 143, level: 'Research', expression: '(A·B+B·C+C·A)⊕(A+B+C)', description: 'XOR of SOP with OR' },
  { id: 144, level: 'Research', expression: "(A·B'+B·C'+C·A')'", description: 'NOR of cyclic' },
  { id: 145, level: 'Research', expression: 'A⊕B+B⊕C+C⊕A', description: 'Triple XOR sum' },
  { id: 146, level: 'Research', expression: '(A⊕B)·(B⊕C)·(C⊕A)', description: 'Triple XOR product' },
  { id: 147, level: 'Research', expression: '(A+B)⊕(B+C)⊕(C+A)', description: 'Triple OR XOR' },
  { id: 148, level: 'Research', expression: "(A·B)'⊕(B·C)'⊕(C·A)'", description: 'Triple NAND XOR' },
  { id: 149, level: 'Research', expression: "A·B·C+A'·B'·C'+A·B'·C'+A'·B·C", description: '4-minterm even' },
  { id: 150, level: 'Research', expression: "A'·B'·C+A·B·C'+A'·B·C'+A·B'·C", description: '4-minterm odd' },
  { id: 151, level: 'Research', expression: "(A·(B+C)')⊕(B·(A+C)')", description: 'NOR XOR' },
  { id: 152, level: 'Research', expression: "(A'·B·C)'+(A·B'·C)'+(A·B·C')'", description: 'Triple NAND sum' },
  { id: 153, level: 'Research', expression: "(A⊕B⊕C)'+A·B·C", description: 'XNOR OR AND' },
  { id: 154, level: 'Research', expression: 'A·(B⊕C)·(A⊕B)·C', description: '4-factor product' },
  { id: 155, level: 'Research', expression: "(A+B·C')·(A'·B+C)", description: 'Complex POS' },
  { id: 156, level: 'Research', expression: "A·B'·C+A'·B·C'+A·B·C", description: '3-minterm' },
  { id: 157, level: 'Research', expression: "A'·(B⊕C)+A·(B⊙C)", description: 'XOR/XNOR mux (⊙=XNOR)' },
  { id: 158, level: 'Research', expression: 'A⊕(B⊙C)', description: 'XOR with XNOR' },
  { id: 159, level: 'Research', expression: 'A⊙(B⊕C)', description: 'XNOR with XOR' },
  { id: 160, level: 'Research', expression: '(A⊕B)⊙(B⊕C)', description: 'XNOR of XORs' },
];

export const LEVELS = ['All', 'Basic', 'Medium', 'Hard', 'Complex', 'Research'];
