// 300+ FBISE & Cambridge Class 11 Logic Design Expressions
// These cover the complete FBISE (Federal Board of Intermediate and Secondary Education, Pakistan)
// and Cambridge O/A Level syllabus for Digital Logic Design

export interface FBISEExpression {
  id: number;
  chapter: string;
  expression: string;
  description: string;
}

export const FBISE_EXPRESSIONS: FBISEExpression[] = [
  // ===== Chapter 1: Basic Logic Gates (1-40) =====
  { id: 1, chapter: 'Basic Gates', expression: 'A+B', description: 'OR gate — output 1 if any input is 1' },
  { id: 2, chapter: 'Basic Gates', expression: 'A·B', description: 'AND gate — output 1 only if all inputs are 1' },
  { id: 3, chapter: 'Basic Gates', expression: "A'", description: 'NOT gate — inverts the input' },
  { id: 4, chapter: 'Basic Gates', expression: "A'+B'", description: 'OR of complements (De Morgan preview)' },
  { id: 5, chapter: 'Basic Gates', expression: "A'·B'", description: 'AND of complements (De Morgan preview)' },
  { id: 6, chapter: 'Basic Gates', expression: "(A+B)'", description: 'NOR gate — NOT of OR' },
  { id: 7, chapter: 'Basic Gates', expression: "(A·B)'", description: 'NAND gate — NOT of AND' },
  { id: 8, chapter: 'Basic Gates', expression: 'A⊕B', description: 'XOR gate — output 1 when inputs differ' },
  { id: 9, chapter: 'Basic Gates', expression: "(A⊕B)'", description: 'XNOR gate — output 1 when inputs same' },
  { id: 10, chapter: 'Basic Gates', expression: 'A+B+C', description: '3-input OR gate' },
  { id: 11, chapter: 'Basic Gates', expression: 'A·B·C', description: '3-input AND gate' },
  { id: 12, chapter: 'Basic Gates', expression: "(A+B+C)'", description: '3-input NOR gate' },
  { id: 13, chapter: 'Basic Gates', expression: "(A·B·C)'", description: '3-input NAND gate' },
  { id: 14, chapter: 'Basic Gates', expression: 'A⊕B⊕C', description: '3-input XOR (odd parity)' },
  { id: 15, chapter: 'Basic Gates', expression: "A'·B'·C'", description: 'All complemented AND' },
  { id: 16, chapter: 'Basic Gates', expression: 'A·B+A·C', description: 'Distributive law: A(B+C)' },
  { id: 17, chapter: 'Basic Gates', expression: '(A+B)·(A+C)', description: 'Distributive law: A+BC' },
  { id: 18, chapter: 'Basic Gates', expression: 'A+A', description: 'Idempotent: A' },
  { id: 19, chapter: 'Basic Gates', expression: 'A·A', description: 'Idempotent: A' },
  { id: 20, chapter: 'Basic Gates', expression: 'A+A·B', description: 'Absorption: A' },
  { id: 21, chapter: 'Basic Gates', expression: 'A·(A+B)', description: 'Absorption: A' },
  { id: 22, chapter: 'Basic Gates', expression: 'A+1', description: 'Null law: 1' },
  { id: 23, chapter: 'Basic Gates', expression: 'A·0', description: 'Null law: 0' },
  { id: 24, chapter: 'Basic Gates', expression: 'A+0', description: 'Identity: A' },
  { id: 25, chapter: 'Basic Gates', expression: 'A·1', description: 'Identity: A' },
  { id: 26, chapter: 'Basic Gates', expression: "A+A'", description: 'Complement: 1' },
  { id: 27, chapter: 'Basic Gates', expression: "A·A'", description: 'Complement: 0' },
  { id: 28, chapter: 'Basic Gates', expression: "A''", description: 'Involution: A' },
  { id: 29, chapter: 'Basic Gates', expression: "A·B+A·B'", description: 'A(B+B\') = A' },
  { id: 30, chapter: 'Basic Gates', expression: "(A+B)·(A+B')", description: 'A+BB\' = A' },
  { id: 31, chapter: 'Basic Gates', expression: 'A+B·C', description: 'SOP with 3 variables' },
  { id: 32, chapter: 'Basic Gates', expression: '(A+B)·C', description: 'POS with 3 variables' },
  { id: 33, chapter: 'Basic Gates', expression: "A'·B+C", description: 'Mixed SOP' },
  { id: 34, chapter: 'Basic Gates', expression: "A·B'+C'", description: 'Mixed SOP' },
  { id: 35, chapter: 'Basic Gates', expression: 'A·(B+C)', description: 'Factored form' },
  { id: 36, chapter: 'Basic Gates', expression: 'A·B+C·D', description: 'Two product terms' },
  { id: 37, chapter: 'Basic Gates', expression: '(A+B)·(C+D)', description: 'Two sum terms' },
  { id: 38, chapter: 'Basic Gates', expression: "A'+B'·C'", description: 'Complemented SOP' },
  { id: 39, chapter: 'Basic Gates', expression: "(A'+B)·C'", description: 'Complemented POS' },
  { id: 40, chapter: 'Basic Gates', expression: 'A⊕B⊕A', description: 'XOR with same variable = 0' },

  // ===== Chapter 2: De Morgan's Theorems (41-70) =====
  { id: 41, chapter: "De Morgan's", expression: "(A·B)'", description: "De Morgan: A'+B'" },
  { id: 42, chapter: "De Morgan's", expression: "(A+B)'", description: "De Morgan: A'·B'" },
  { id: 43, chapter: "De Morgan's", expression: "(A·B·C)'", description: "De Morgan 3-var: A'+B'+C'" },
  { id: 44, chapter: "De Morgan's", expression: "(A+B+C)'", description: "De Morgan 3-var: A'·B'·C'" },
  { id: 45, chapter: "De Morgan's", expression: "(A·B+C)'", description: "De Morgan mixed" },
  { id: 46, chapter: "De Morgan's", expression: "(A+B·C)'", description: "De Morgan mixed" },
  { id: 47, chapter: "De Morgan's", expression: "(A'+B')'", description: "Double De Morgan: A·B" },
  { id: 48, chapter: "De Morgan's", expression: "(A'·B')'", description: "Double De Morgan: A+B" },
  { id: 49, chapter: "De Morgan's", expression: "((A+B)·C)'", description: "Nested De Morgan" },
  { id: 50, chapter: "De Morgan's", expression: "((A·B)+C)'", description: "Nested De Morgan" },
  { id: 51, chapter: "De Morgan's", expression: "(A·B)'·(C·D)'", description: "Product of NANDs" },
  { id: 52, chapter: "De Morgan's", expression: "(A+B)'+(C+D)'", description: "Sum of NORs" },
  { id: 53, chapter: "De Morgan's", expression: "(A·B)'+(A+B)'", description: "NAND + NOR" },
  { id: 54, chapter: "De Morgan's", expression: "(A⊕B)'", description: "XNOR = (A·B)+(A'·B')" },
  { id: 55, chapter: "De Morgan's", expression: "(A·B)'·(A'·B')'", description: "Complex De Morgan" },
  { id: 56, chapter: "De Morgan's", expression: "(A+B+C)'·(A·B·C)'", description: '3-var De Morgan product' },
  { id: 57, chapter: "De Morgan's", expression: "((A·B)')'", description: 'Double NOT = A·B' },
  { id: 58, chapter: "De Morgan's", expression: "((A+B)')'", description: 'Double NOT = A+B' },
  { id: 59, chapter: "De Morgan's", expression: "(A·(B+C))'", description: 'De Morgan on factored' },
  { id: 60, chapter: "De Morgan's", expression: '((A+B)·(C+D))\'', description: 'De Morgan on product of sums' },
  { id: 61, chapter: "De Morgan's", expression: "(A·B+C·D)'", description: 'De Morgan on two products' },
  { id: 62, chapter: "De Morgan's", expression: "A'·B'+A·B", description: 'XNOR using De Morgan' },
  { id: 63, chapter: "De Morgan's", expression: "A'·B+A·B'", description: 'XOR using De Morgan' },
  { id: 64, chapter: "De Morgan's", expression: "(A'+B)'", description: 'Simplify to A·B\'' },
  { id: 65, chapter: "De Morgan's", expression: "(A·B')'", description: 'Simplify to A\'+B' },
  { id: 66, chapter: "De Morgan's", expression: "(A'+B')·(A+B)", description: 'De Morgan application' },
  { id: 67, chapter: "De Morgan's", expression: "(A·B+A'·B')'", description: 'NOT of XNOR = XOR' },
  { id: 68, chapter: "De Morgan's", expression: "(A·B'+A'·B)'", description: 'NOT of XOR = XNOR' },
  { id: 69, chapter: "De Morgan's", expression: "((A+B)·(C+D))'+(A·B·C)'", description: 'Complex De Morgan' },
  { id: 70, chapter: "De Morgan's", expression: "(A·B·C)'·(A+B+C)'", description: 'NAND AND NOR' },

  // ===== Chapter 3: Boolean Algebra Simplification (71-110) =====
  { id: 71, chapter: 'Simplification', expression: 'A·B+A·B·C', description: 'Absorption: A·B' },
  { id: 72, chapter: 'Simplification', expression: 'A+A·B', description: 'Absorption: A' },
  { id: 73, chapter: 'Simplification', expression: 'A·(A+B)', description: 'Absorption: A' },
  { id: 74, chapter: 'Simplification', expression: 'A·B+A·C+B·C', description: 'Consensus: AB+AC' },
  { id: 75, chapter: 'Simplification', expression: '(A+B)·(A+C)·(B+C)', description: 'Consensus POS' },
  { id: 76, chapter: 'Simplification', expression: "A·B+A'·C+B·C", description: 'Consensus: AB+A\'C' },
  { id: 77, chapter: 'Simplification', expression: "A·B'+A'·B+B'·C", description: 'Consensus variant' },
  { id: 78, chapter: 'Simplification', expression: 'A·(B+C)+B·C', description: 'Factored with consensus' },
  { id: 79, chapter: 'Simplification', expression: 'A+B·C+A·B', description: 'Absorption + factoring' },
  { id: 80, chapter: 'Simplification', expression: "A·B·C+A·B·C'+A·B'·C", description: 'Simplify: AB+AC' },
  { id: 81, chapter: 'Simplification', expression: "A'·B'·C+A'·B·C'+AB'·C'", description: '3-minterm simplify' },
  { id: 82, chapter: 'Simplification', expression: 'A·B+A·C+A·D', description: 'Factor: A(B+C+D)' },
  { id: 83, chapter: 'Simplification', expression: 'A·(B+C)+B·(C+D)', description: 'Expand and simplify' },
  { id: 84, chapter: 'Simplification', expression: "(A+B)·(A+C)+B·C", description: 'POS simplification' },
  { id: 85, chapter: 'Simplification', expression: "A·B·C+A'·B+A·B'·C", description: 'Multi-term SOP' },
  { id: 86, chapter: 'Simplification', expression: "A+A'·B", description: 'Simplify: A+B' },
  { id: 87, chapter: 'Simplification', expression: "A·(A'+B)", description: 'Simplify: A·B' },
  { id: 88, chapter: 'Simplification', expression: "A·B+A'·C+B·C·D", description: 'Extended consensus' },
  { id: 89, chapter: 'Simplification', expression: "(A+B)·(A'+C)", description: 'POS to SOP' },
  { id: 90, chapter: 'Simplification', expression: "A·B·C+A·B'·C+A'·B·C", description: '3-minterm K-map' },
  { id: 91, chapter: 'Simplification', expression: "A·B·C'+A·B'·C+A'·B·C", description: '3-minterm SOP' },
  { id: 92, chapter: 'Simplification', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+AB'·C'", description: '4-minterm' },
  { id: 93, chapter: 'Simplification', expression: "A+B·(A+C)", description: 'Simplify: A+BC' },
  { id: 94, chapter: 'Simplification', expression: "A·B+A·C+B·C+C·D", description: '4-term consensus' },
  { id: 95, chapter: 'Simplification', expression: "(A+B+C)·(A+B+C')", description: 'POS simplify: A+B' },
  { id: 96, chapter: 'Simplification', expression: "(A+B+C)·(A+B'+C)", description: 'POS simplify: A+C' },
  { id: 97, chapter: 'Simplification', expression: "(A+B)·(A+B')", description: 'Simplify: A' },
  { id: 98, chapter: 'Simplification', expression: "A·B+A·B'", description: 'Simplify: A' },
  { id: 99, chapter: 'Simplification', expression: "(A+B)·(A'+B)", description: 'Simplify: B' },
  { id: 100, chapter: 'Simplification', expression: "A·B'+A·B", description: 'Simplify: A' },
  { id: 101, chapter: 'Simplification', expression: 'A·B·C+A·B+A', description: 'Absorption chain: A' },
  { id: 102, chapter: 'Simplification', expression: 'A+B+C+A·B', description: 'Absorption: A+B+C' },
  { id: 103, chapter: 'Simplification', expression: "A·B·C'+A·B'·C+A·B·C", description: 'Simplify: A·B+A·C' },
  { id: 104, chapter: 'Simplification', expression: "A'·B+A·B'+A·B", description: 'Simplify: A+B' },
  { id: 105, chapter: 'Simplification', expression: "A·B·C+A·B·C'+A'·B·C", description: 'Simplify: AB+BC' },
  { id: 106, chapter: 'Simplification', expression: "(A·B+C)·(A·B+D)", description: 'Factor: AB+CD' },
  { id: 107, chapter: 'Simplification', expression: "A·B·C·D+A·B·C·D'+A·B·C'·D", description: '4-var simplify' },
  { id: 108, chapter: 'Simplification', expression: "A'·B'·C'+A'·B·C'+A·B'·C'", description: '3-minterm' },
  { id: 109, chapter: 'Simplification', expression: "A+B'·C+A·B", description: 'Absorption: A+B\'C' },
  { id: 110, chapter: 'Simplification', expression: "(A+B+C)·(A'+B'+C')", description: 'Complement product' },

  // ===== Chapter 4: Combinational Circuits (111-160) =====
  { id: 111, chapter: 'Combinational', expression: 'A⊕B', description: 'Half Adder Sum' },
  { id: 112, chapter: 'Combinational', expression: 'A·B', description: 'Half Adder Carry' },
  { id: 113, chapter: 'Combinational', expression: 'A⊕B⊕C', description: 'Full Adder Sum' },
  { id: 114, chapter: 'Combinational', expression: 'A·B+B·C+A·C', description: 'Full Adder Carry' },
  { id: 115, chapter: 'Combinational', expression: 'A⊕B', description: 'Half Subtractor Difference' },
  { id: 116, chapter: 'Combinational', expression: "A'·B", description: 'Half Subtractor Borrow' },
  { id: 117, chapter: 'Combinational', expression: 'A⊕B⊕C', description: 'Full Subtractor Difference' },
  { id: 118, chapter: 'Combinational', expression: "A'·B+B'·C+A'·C", description: 'Full Subtractor Borrow' },
  { id: 119, chapter: 'Combinational', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+AB'·C'", description: 'BCD to Excess-3 bit 0' },
  { id: 120, chapter: 'Combinational', expression: "B'·C+B·C'", description: 'BCD to Excess-3 bit 1 (B⊕C)' },
  { id: 121, chapter: 'Combinational', expression: "A+B+C'", description: 'BCD to Excess-3 bit 2' },
  { id: 122, chapter: 'Combinational', expression: "A'·B'·C'+A'·B'·C+AB'·C'+ABC", description: 'Even parity checker' },
  { id: 123, chapter: 'Combinational', expression: "A'·B'·C+A'·B·C'+AB'·C+ABC'", description: 'Odd parity checker' },
  { id: 124, chapter: 'Combinational', expression: "A'·B'·C+A'·B·C+AB'·C+ABC", description: 'Odd parity generator' },
  { id: 125, chapter: 'Combinational', expression: "A'·B'·C'+A'·B·C+AB'·C'+ABC", description: 'Even parity generator' },
  { id: 126, chapter: 'Combinational', expression: 'A·B+A·C+B·C', description: '3-bit Majority Function' },
  { id: 127, chapter: 'Combinational', expression: "A'·B'·C+A·B'·C'+A'·B·C'+ABC", description: '4-minterm even parity' },
  { id: 128, chapter: 'Combinational', expression: "A·B'+A'·B", description: 'XOR via AND/OR/NOT' },
  { id: 129, chapter: 'Combinational', expression: "A·B+A'·B'", description: 'XNOR via AND/OR/NOT' },
  { id: 130, chapter: 'Combinational', expression: 'A·B·C+A·D', description: '4-variable SOP' },
  { id: 131, chapter: 'Combinational', expression: "(A+B)·(C+D)", description: '4-variable POS' },
  { id: 132, chapter: 'Combinational', expression: "A·B·C·D+A'·B'·C'·D'", description: '2 minterms 4-var' },
  { id: 133, chapter: 'Combinational', expression: "A·B+C·D+A·C+B·D", description: '4-term SOP' },
  { id: 134, chapter: 'Combinational', expression: "A'·B·C+A·B'·C+A·B·C'", description: '3-minterm (1,5,6,7 pattern)' },
  { id: 135, chapter: 'Combinational', expression: "A'·B'+A·B", description: 'XNOR equality checker' },
  { id: 136, chapter: 'Combinational', expression: "A'·B+A·B'", description: 'XOR difference detector' },
  { id: 137, chapter: 'Combinational', expression: 'A⊕B⊕C⊕D', description: '4-input XOR (parity)' },
  { id: 138, chapter: 'Combinational', expression: 'A·B+B·C+C·D+D·A', description: '4-variable cyclic' },
  { id: 139, chapter: 'Combinational', expression: "A·B'+B·C'+C·D'+D·A'", description: '4-variable cyclic complemented' },
  { id: 140, chapter: 'Combinational', expression: "A'·B'·C'+A·B·C", description: 'All same checker' },
  { id: 141, chapter: 'Combinational', expression: "A+B+C+D", description: '4-input OR' },
  { id: 142, chapter: 'Combinational', expression: 'A·B·C·D', description: '4-input AND' },
  { id: 143, chapter: 'Combinational', expression: "(A+B+C+D)'", description: '4-input NOR' },
  { id: 144, chapter: 'Combinational', expression: "(A·B·C·D)'", description: '4-input NAND' },
  { id: 145, chapter: 'Combinational', expression: "A·(B⊕C)", description: 'AND with XOR' },
  { id: 146, chapter: 'Combinational', expression: 'A⊕(B+C)', description: 'XOR with OR' },
  { id: 147, chapter: 'Combinational', expression: 'A⊕(B·C)', description: 'XOR with AND' },
  { id: 148, chapter: 'Combinational', expression: "(A⊕B)·C", description: 'XOR ANDed with C' },
  { id: 149, chapter: 'Combinational', expression: "(A⊕B)+C", description: 'XOR ORed with C' },
  { id: 150, chapter: 'Combinational', expression: "A·(B+C)+B·(A+C)", description: 'Symmetric expression' },
  { id: 151, chapter: 'Combinational', expression: "A'·B+A·B'+C", description: 'XOR with extra input' },
  { id: 152, chapter: 'Combinational', expression: "(A+B)·(B+C)·(A+C)", description: '3-factor POS majority' },
  { id: 153, chapter: 'Combinational', expression: "A·B·C+A'·B'·C'", description: 'Complement pair' },
  { id: 154, chapter: 'Combinational', expression: "A·B'+A'·B+C·D", description: 'XOR + AND term' },
  { id: 155, chapter: 'Combinational', expression: "(A·B⊕C)·(A+B·C')", description: 'Complex combinational' },
  { id: 156, chapter: 'Combinational', expression: "A·(B⊕C)+B·(A⊕C)", description: 'Double XOR network' },
  { id: 157, chapter: 'Combinational', expression: "A·B·C+A·B'·C+A'·B·C", description: '3-minterm majority variant' },
  { id: 158, chapter: 'Combinational', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+AB'·C'+A'·B·C+AB'·C+ABC'+ABC", description: 'All minterms = 1' },
  { id: 159, chapter: 'Combinational', expression: "A·B+A'·C", description: 'Simple SOP' },
  { id: 160, chapter: 'Combinational', expression: "(A+B)·(A'+C)", description: 'Simple POS' },

  // ===== Chapter 5: K-Map Problems (161-220) =====
  { id: 161, chapter: 'K-Map', expression: "A'·B'·C+A'·B·C+A·B'·C+A·B·C", description: 'Σm(1,3,5,7) = C' },
  { id: 162, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C'+A·B'·C'+A·B·C'", description: 'Σm(0,2,4,6) = C\'' },
  { id: 163, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A'·B·C+AB·C", description: 'Σm(0,1,3,7)' },
  { id: 164, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C'+A·B'·C'+AB·C", description: 'Σm(0,2,4,7)' },
  { id: 165, chapter: 'K-Map', expression: "A'·B'·C+A'·B·C+AB'·C+ABC", description: 'Σm(1,3,5,7) = C' },
  { id: 166, chapter: 'K-Map', expression: "A'·B'+A·B", description: 'XNOR = equality' },
  { id: 167, chapter: 'K-Map', expression: "A'·B+A·B'", description: 'XOR = difference' },
  { id: 168, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C'+A'·B·C+A·B·C", description: 'Σm(0,2,3,7)' },
  { id: 169, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A·B'·C+ABC", description: 'Σm(0,1,5,7) = B\'C + AC' },
  { id: 170, chapter: 'K-Map', expression: "A'·B·C'+A·B'·C'+AB'·C+A'·B·C", description: 'Σm(2,4,5,3)' },
  { id: 171, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+A·B'·C'", description: 'Σm(0,1,2,4) = A\'B\' + B\'C\'' },
  { id: 172, chapter: 'K-Map', expression: "A'·B'·C+A·B'·C+A·B·C'+A'·B·C'", description: 'Σm(1,5,6,2)' },
  { id: 173, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C+A·B'·C+ABC'", description: 'Σm(0,3,5,6)' },
  { id: 174, chapter: 'K-Map', expression: "A'·B·C'+A'·B·C+A·B'·C+ABC", description: 'Σm(2,3,5,7) = BC + A\'C' },
  { id: 175, chapter: 'K-Map', expression: "A'·B'·C'+A·B·C'+A·B'·C+ABC", description: 'Σm(0,5,7,4) = AC + B\'C\'' },
  { id: 176, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+A'·B·C+AB'·C'+AB'·C+ABC'+ABC", description: 'All = 1' },
  { id: 177, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+A'·B·C", description: 'Σm(0,1,2,3) = A\'' },
  { id: 178, chapter: 'K-Map', expression: "AB'·C'+AB'·C+ABC'+ABC", description: 'Σm(4,5,6,7) = A' },
  { id: 179, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C'+AB'·C'+AB·C'", description: 'Σm(0,2,4,6) = C\'' },
  { id: 180, chapter: 'K-Map', expression: "A'·B'·C+A'·B·C+AB'·C+AB·C", description: 'Σm(1,3,5,7) = C' },
  { id: 181, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A·B'·C'+A·B'·C", description: 'Σm(0,1,4,5) = B\'' },
  { id: 182, chapter: 'K-Map', expression: "A'·B·C'+A'·B·C+A·B·C'+A·B·C", description: 'Σm(2,3,6,7) = B' },
  { id: 183, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C'+AB'·C'+AB·C'", description: 'Σm(0,2,4,6) = C\'' },
  { id: 184, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+A'·B·C+AB'·C'+AB'·C", description: 'Σm(0,1,2,3,4,5) = A\'+B\'' },
  { id: 185, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A'·B·C+AB'·C+ABC", description: 'Σm(0,1,3,5,7) = C + A\'B\'' },
  { id: 186, chapter: 'K-Map', expression: "A'·B'·C+A'·B·C'+A·B'·C+ABC", description: 'Σm(1,2,5,7)' },
  { id: 187, chapter: 'K-Map', expression: "A'·B'·C'+A·B·C'+A·B'·C+ABC", description: 'Σm(0,5,7,4)' },
  { id: 188, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C+AB'·C+ABC", description: 'Σm(0,3,5,7) = C' },
  { id: 189, chapter: 'K-Map', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+AB'·C'", description: 'Σm(0,1,2,4)' },
  { id: 190, chapter: 'K-Map', expression: "A'·B·C'+A·B'·C'+A'·B·C+A·B'·C", description: 'Σm(2,3,4,5) = B⊕C' },
  { id: 191, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C+A·B'·C+A·B·C'", description: 'Σm(0,3,5,6) = XOR' },
  { id: 192, chapter: 'K-Map', expression: "A'·B'·C+A'·B·C'+A·B'·C'+ABC", description: 'Σm(1,2,4,7) = XOR' },
  { id: 193, chapter: 'K-Map', expression: "A'·B'·C'+A'·B·C+A·B'·C+ABC'", description: 'Σm(0,3,5,6) = XNOR' },
  { id: 194, chapter: 'K-Map', expression: "A'·B'·C+A'·B·C'+A·B'·C'+ABC", description: 'Σm(1,2,4,7) = XOR 3' },
  { id: 195, chapter: 'K-Map', expression: "A·B·C·D+A'·B'·C'·D'+A·B'·C·D'+A'·B·C'·D", description: '4-var 4-minterm' },
  { id: 196, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B'·C·D'+A'·B·C'·D'+A'·B·C·D'", description: 'Σm(0,2,4,6) 4-var' },
  { id: 197, chapter: 'K-Map', expression: "A'·B'·C'·D+A'·B'·C·D+A'·B·C'·D+A'·B·C·D", description: 'Σm(1,3,5,7) 4-var = A\'D' },
  { id: 198, chapter: 'K-Map', expression: "A·B'·C'·D+A·B'·C·D+A·B·C'·D+A·B·C·D", description: 'Σm(9,11,13,15) = AD' },
  { id: 199, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B'·C'·D+A'·B'·C·D'+A'·B'·C·D", description: 'Σm(0,1,2,3) = A\'B\'' },
  { id: 200, chapter: 'K-Map', expression: "A·B·C'·D'+A·B·C'·D+A·B·C·D'+A·B·C·D", description: 'Σm(12,13,14,15) = AB' },
  { id: 201, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B·C'·D'+A·B'·C'·D'+A·B·C'·D'", description: 'Σm(0,4,8,12) = C\'D\'' },
  { id: 202, chapter: 'K-Map', expression: "A'·B'·C·D'+A'·B·C·D'+A·B'·C·D'+A·B·C·D'", description: 'Σm(2,6,10,14) = CD\'' },
  { id: 203, chapter: 'K-Map', expression: "A'·B'·C'·D+A'·B·C'·D+A·B'·C'·D+A·B·C'·D", description: 'Σm(1,5,9,13) = C\'D' },
  { id: 204, chapter: 'K-Map', expression: "A'·B'·C·D+A'·B·C·D+A·B'·C·D+A·B·C·D", description: 'Σm(3,7,11,15) = CD' },
  { id: 205, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B'·C'·D+A·B'·C'·D'+A·B'·C'·D", description: 'Σm(0,1,8,9) = B\'C\'' },
  { id: 206, chapter: 'K-Map', expression: "A'·B·C'·D'+A'·B·C'·D+A·B·C'·D'+A·B·C'·D", description: 'Σm(4,5,12,13) = BC\'' },
  { id: 207, chapter: 'K-Map', expression: "A'·B'·C·D'+A'·B'·C·D+A·B'·C·D'+A·B'·C·D", description: 'Σm(2,3,10,11) = B\'C' },
  { id: 208, chapter: 'K-Map', expression: "A'·B·C·D'+A'·B·C·D+A·B·C·D'+A·B·C·D", description: 'Σm(6,7,14,15) = BC' },
  { id: 209, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B'·C'·D+A'·B'·C·D+A'·B·C'·D'+A'·B·C·D+A·B'·C'·D'+A·B'·C·D+A·B·C'·D", description: 'Σm(0,1,3,4,6,8,10,11)' },
  { id: 210, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B'·C·D'+A'·B·C'·D'+A'·B·C·D'+A·B'·C'·D'+A·B'·C·D'+A·B·C'·D'+A·B·C·D'", description: 'Σm(0,2,4,6,8,10,12,14) = D\'' },
  { id: 211, chapter: 'K-Map', expression: "A'·B'·C'·D+A'·B'·C·D+A'·B·C'·D+A'·B·C·D+A·B'·C'·D+A·B'·C·D+A·B·C'·D+A·B·C·D", description: 'Σm(1,3,5,7,9,11,13,15) = D' },
  { id: 212, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B'·C'·D+A'·B'·C·D'+A'·B·C'·D'+A·B'·C'·D'+A·B'·C'·D+A·B'·C·D'+A·B·C'·D'", description: 'Σm(0,1,2,4,8,9,10,12)' },
  { id: 213, chapter: 'K-Map', expression: "A'·B'·C·D+A'·B·C'·D+A'·B·C·D'+A·B'·C'·D+A·B'·C·D'+A·B·C'·D'", description: 'Σm(3,5,6,9,10,12)' },
  { id: 214, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B·C'·D+A·B'·C·D'+ABC·D", description: 'Σm(0,5,10,15)' },
  { id: 215, chapter: 'K-Map', expression: "A'·B'·C'·D+A'·B·C'·D'+A·B'·C·D'+ABC·D'", description: 'Σm(1,4,10,14)' },
  { id: 216, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B'·C·D+A'·B·C'·D+A·B'·C'·D'+A·B·C·D'", description: 'Σm(0,3,5,8,14)' },
  { id: 217, chapter: 'K-Map', expression: "A'·B·C·D'+A·B'·C'·D+A·B·C'·D'+A'·B'·C·D", description: 'Σm(6,9,12,3)' },
  { id: 218, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B'·C·D'+A'·B·C·D'+A'·B·C·D+A·B'·C'·D'+A·B'·C·D'+A·B·C·D'+A·B·C·D", description: 'Σm(0,2,6,7,8,10,14,15)' },
  { id: 219, chapter: 'K-Map', expression: "A'·B'·C'·D+A'·B'·C·D+A'·B·C'·D+A'·B·C·D+A·B'·C'·D+A·B'·C·D+A·B·C'·D+A·B·C·D", description: 'Σm(1,3,5,7,9,11,13,15) = D' },
  { id: 220, chapter: 'K-Map', expression: "A'·B'·C'·D'+A'·B·C'·D'+A·B'·C'·D'+A·B·C'·D'+A'·B'·C·D'+A'·B·C·D'+A·B'·C·D'+A·B·C·D'", description: 'Σm(0,4,8,12,2,6,10,14) = D\'' },

  // ===== Chapter 6: Standard Forms & Minterm/Maxterm (221-260) =====
  { id: 221, chapter: 'Standard Forms', expression: "A'·B·C+A·B'·C'+ABC", description: '3-minterm canonical SOP' },
  { id: 222, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B'+C')·(A'+B+C')", description: '3-maxterm canonical POS' },
  { id: 223, chapter: 'Standard Forms', expression: "A'·B'·C+A'·B·C+AB'·C+ABC", description: 'Σm(1,3,5,7) canonical' },
  { id: 224, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B+C')·(A+B'+C)·(A'+B+C)", description: 'ΠM(0,1,2,4) POS' },
  { id: 225, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B·C+AB'·C+ABC'", description: 'Σm(0,3,5,6) XNOR' },
  { id: 226, chapter: 'Standard Forms', expression: "A'·B'·C+A'·B·C'+AB'·C'+ABC", description: 'Σm(1,2,4,7) XOR' },
  { id: 227, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B·C'+A'·B·C+ABC", description: 'Σm(0,2,3,7)' },
  { id: 228, chapter: 'Standard Forms', expression: "(A+B+C')·(A+B'+C)·(A'+B+C)", description: 'ΠM(1,2,4)' },
  { id: 229, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+A·B'·C'", description: 'Σm(0,1,2,4)' },
  { id: 230, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B'+C')·(A'+B'+C)", description: 'ΠM(0,3,6)' },
  { id: 231, chapter: 'Standard Forms', expression: "A'·B·C+A·B'·C+A·B·C'+A'·B·C'", description: 'Σm(2,3,5,6) B⊕C' },
  { id: 232, chapter: 'Standard Forms', expression: "(A+B+C)·(A'+B'+C')", description: 'ΠM(0,7)' },
  { id: 233, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B·C+A·B'·C+ABC", description: 'Σm(0,3,5,7) XNOR' },
  { id: 234, chapter: 'Standard Forms', expression: "(A+B+C')·(A+B'+C')·(A'+B+C')·(A'+B'+C')", description: 'ΠM(1,3,5,7) = C\'' },
  { id: 235, chapter: 'Standard Forms', expression: "A'·B'·C'+A·B'·C'+A'·B·C'+A·B·C'", description: 'Σm(0,2,4,6) = C\'' },
  { id: 236, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B+C')·(A+B'+C)·(A+B'+C')·(A'+B+C)·(A'+B+C')·(A'+B'+C)·(A'+B'+C')", description: 'ΠM(all) = 0' },
  { id: 237, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+A'·B·C+AB'·C'+AB'·C+ABC'+ABC", description: 'Σm(all) = 1' },
  { id: 238, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B·C+AB'·C+ABC", description: 'Σm(0,3,5,7)' },
  { id: 239, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B'+C')·(A'+B+C')·(A'+B'+C)", description: 'ΠM(0,3,5,6)' },
  { id: 240, chapter: 'Standard Forms', expression: "A·B·C+A'·B'·C'+A·B'·C+A'·B·C'", description: 'Σm(0,3,5,7) variant' },
  { id: 241, chapter: 'Standard Forms', expression: "(A+B+C')·(A'+B'+C)", description: 'ΠM(1,6)' },
  { id: 242, chapter: 'Standard Forms', expression: "A'·B'·C+A·B·C", description: 'Σm(1,7) = BC' },
  { id: 243, chapter: 'Standard Forms', expression: "(A+B+C)·(A'+B'+C')", description: 'ΠM(0,7)' },
  { id: 244, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B·C'+A·B'·C+ABC", description: 'Σm(0,2,5,7)' },
  { id: 245, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B+C')·(A'+B'+C)·(A'+B'+C')", description: 'ΠM(0,1,6,7) = A\' + B\'' },
  { id: 246, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B'·C+A·B·C'+A·B·C", description: 'Σm(0,1,6,7) = A⊕B' },
  { id: 247, chapter: 'Standard Forms', expression: "(A+B+C')·(A+B'+C')·(A'+B+C')·(A'+B'+C')", description: 'ΠM(1,3,5,7) = C\'' },
  { id: 248, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+A'·B·C", description: 'Σm(0,1,2,3) = A\'' },
  { id: 249, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B+C')·(A+B'+C)·(A+B'+C')", description: 'ΠM(0,1,2,3) = A' },
  { id: 250, chapter: 'Standard Forms', expression: "A'·B'·C+A'·B·C'+A·B'·C'+A·B·C", description: 'Σm(1,2,4,7) = A⊕B⊕C' },
  { id: 251, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B·C+A·B'·C+A·B·C'", description: 'Σm(0,3,5,6) = XNOR' },
  { id: 252, chapter: 'Standard Forms', expression: "A'·B·C+A·B'·C+A·B·C'+A'·B'·C'", description: 'Σm(0,3,5,6) reindexed' },
  { id: 253, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B·C'+A·B'·C+ABC", description: 'Σm(0,2,5,7)' },
  { id: 254, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B'+C')·(A'+B+C)·(A'+B'+C')", description: 'ΠM(0,3,4,7)' },
  { id: 255, chapter: 'Standard Forms', expression: "A'·B'·C+A·B'·C'+A'·B·C'+ABC", description: 'Σm(1,2,4,7)' },
  { id: 256, chapter: 'Standard Forms', expression: "A'·B'·C'+AB'·C'+A'·B·C+ABC", description: 'Σm(0,2,3,7) = A\'C + B\'C\'' },
  { id: 257, chapter: 'Standard Forms', expression: "(A+B+C')·(A+B'+C')·(A'+B+C)·(A'+B'+C)", description: 'ΠM(1,3,4,6)' },
  { id: 258, chapter: 'Standard Forms', expression: "A'·B'·C'+A'·B'·C+A·B'·C'+A·B'·C", description: 'Σm(0,1,4,5) = B\'' },
  { id: 259, chapter: 'Standard Forms', expression: "(A+B+C)·(A+B+C')·(A'+B+C)·(A'+B+C')", description: 'ΠM(0,1,4,5) = B' },
  { id: 260, chapter: 'Standard Forms', expression: "A'·B·C'+A'·B·C+A·B·C'+A·B·C", description: 'Σm(2,3,6,7) = B' },

  // ===== Chapter 7: Cambridge O/A Level Problems (261-300) =====
  { id: 261, chapter: 'Cambridge', expression: 'A·B+A·C+B·C', description: 'Cambridge: Majority function' },
  { id: 262, chapter: 'Cambridge', expression: "A'·B+A·B'", description: 'Cambridge: XOR (half adder sum)' },
  { id: 263, chapter: 'Cambridge', expression: 'A·B', description: 'Cambridge: AND (half adder carry)' },
  { id: 264, chapter: 'Cambridge', expression: 'A⊕B⊕C', description: 'Cambridge: Full adder sum' },
  { id: 265, chapter: 'Cambridge', expression: 'A·B+(A⊕B)·C', description: 'Cambridge: Full adder carry' },
  { id: 266, chapter: 'Cambridge', expression: "A'·B", description: 'Cambridge: Half subtractor borrow' },
  { id: 267, chapter: 'Cambridge', expression: "A⊕B⊕C", description: 'Cambridge: Full subtractor diff' },
  { id: 268, chapter: 'Cambridge', expression: "A'·B+B'·C+A'·C", description: 'Cambridge: Full subtractor borrow' },
  { id: 269, chapter: 'Cambridge', expression: "A'·B'·C+A·B'·C'+A·B·C'", description: 'Cambridge: 3-minterm problem' },
  { id: 270, chapter: 'Cambridge', expression: "(A+B)·(B+C)·(A+C)", description: 'Cambridge: 3-factor POS' },
  { id: 271, chapter: 'Cambridge', expression: "A·B·C+A'·B·C+A·B'·C+A·B·C'", description: 'Cambridge: At least 2 of 3' },
  { id: 272, chapter: 'Cambridge', expression: "A'·B'·C'+A'·B·C'+A·B'·C'+A·B·C'", description: 'Cambridge: C=0 cases' },
  { id: 273, chapter: 'Cambridge', expression: "A'·B'·C+A'·B·C+AB'·C+AB·C", description: 'Cambridge: C=1 cases' },
  { id: 274, chapter: 'Cambridge', expression: "A'·B'·C'+A'·B'·C+A'·B·C+AB·C", description: 'Cambridge: 4-minterm' },
  { id: 275, chapter: 'Cambridge', expression: "A·B+A'·C", description: 'Cambridge: Simple SOP' },
  { id: 276, chapter: 'Cambridge', expression: "(A+B)·(A'+C)", description: 'Cambridge: Simple POS' },
  { id: 277, chapter: 'Cambridge', expression: "A·B'+A'·B+C", description: 'Cambridge: XOR + C' },
  { id: 278, chapter: 'Cambridge', expression: "(A⊕B)·C", description: 'Cambridge: XOR ANDed' },
  { id: 279, chapter: 'Cambridge', expression: "A·(B⊕C)", description: 'Cambridge: AND + XOR' },
  { id: 280, chapter: 'Cambridge', expression: "A'·B·C+A·B'·C+A·B·C'+A'·B'·C'", description: 'Cambridge: Even parity' },
  { id: 281, chapter: 'Cambridge', expression: "A'·B'·C+A'·B·C'+A·B'·C'+ABC", description: 'Cambridge: Odd parity' },
  { id: 282, chapter: 'Cambridge', expression: "A·B·C·D+A·B·C·D'+A·B·C'·D+A·B'·C·D+A'·B·C·D", description: 'Cambridge: 4-var 5-minterm' },
  { id: 283, chapter: 'Cambridge', expression: "A'·B'·C'·D'+A'·B'·C·D'+A'·B·C'·D'+A'·B·C·D'+AB'·C'·D'+AB'·C·D'+AB·C'·D'+AB·C·D'", description: 'Cambridge: All D=0' },
  { id: 284, chapter: 'Cambridge', expression: "A·B+A·C+A·D+B·C+B·D+C·D", description: 'Cambridge: At least 2 of 4' },
  { id: 285, chapter: 'Cambridge', expression: "A'·B'·C'·D'+A·B·C·D", description: 'Cambridge: All 0 or all 1' },
  { id: 286, chapter: 'Cambridge', expression: "(A+B)·(C+D)", description: 'Cambridge: Two 2-input ORs ANDed' },
  { id: 287, chapter: 'Cambridge', expression: "A·B+C·D", description: 'Cambridge: Two 2-input ANDs ORed' },
  { id: 288, chapter: 'Cambridge', expression: "A⊕B⊕C⊕D", description: 'Cambridge: 4-input XOR parity' },
  { id: 289, chapter: 'Cambridge', expression: "A'·B·C·D+A·B'·C·D+A·B·C'·D+A·B·C·D'", description: 'Cambridge: Exactly one 0' },
  { id: 290, chapter: 'Cambridge', expression: "A'·B'·C'·D+A'·B'·C·D'+A'·B·C'·D'+A'·B·C·D+AB'·C'·D'+AB'·C·D+AB·C'·D+ABC·D'", description: 'Cambridge: Odd parity 4-var' },
  { id: 291, chapter: 'Cambridge', expression: "A·B·C'+A·B'·C+A'·B·C", description: 'Cambridge: Exactly 2 of 3 are 1' },
  { id: 292, chapter: 'Cambridge', expression: "A'·B'·C'+A'·B'·C+A'·B·C'+AB'·C'", description: 'Cambridge: At most 1 is 1' },
  { id: 293, chapter: 'Cambridge', expression: "A+B+C+A·B+B·C+A·C", description: 'Cambridge: At least 1 of 3 (redundant)' },
  { id: 294, chapter: 'Cambridge', expression: "A·B·C+A'·B'·C'+A'·B·C+AB'·C'", description: 'Cambridge: A=B=C' },
  { id: 295, chapter: 'Cambridge', expression: "(A⊕B)+(B⊕C)", description: 'Cambridge: Two XORs ORed' },
  { id: 296, chapter: 'Cambridge', expression: "(A⊕B)·(B⊕C)", description: 'Cambridge: Two XORs ANDed' },
  { id: 297, chapter: 'Cambridge', expression: "A'·(B+C)+B·(A+C')", description: 'Cambridge: Complex expression' },
  { id: 298, chapter: 'Cambridge', expression: "(A+B')·(B+C')·(A'+C)", description: 'Cambridge: 3-factor POS' },
  { id: 299, chapter: 'Cambridge', expression: "A·B·C+A'·B+A·B'·C", description: 'Cambridge: Simplify to AB+BC' },
  { id: 300, chapter: 'Cambridge', expression: "A+A'·B·C", description: 'Cambridge: Simplify to A+BC' },
];

export const FBISE_CHAPTERS = [
  'All',
  'Basic Gates',
  "De Morgan's",
  'Simplification',
  'Combinational',
  'K-Map',
  'Standard Forms',
  'Cambridge',
];
